### ISSUE TITLE
useViewportScroll has been depreciated

### ISSUE THREAD

**Issue by MrUltimate** [breadadams/scroller-motion#27]
https://github.com/framer/motion/blob/main/CHANGELOG.md#deprecated

**Comment by breadadams** [comment]
Thanks for notifying @MrUltimate, I'll try and add support for v6.5.0 in the following days 👍

**Comment by MrUltimate** [comment]
Hey @breadadams, thanks for dealing with this so quickly! I had another question I wanted to ask you: I'm building scroll based animations that rely on `scroller-motion` however, disabling it for mobile unmounts it completely. Is there a better way to keep existing animations on mobile without writing all the animation logic with native scroll fallbacks?

**Comment by breadadams** [comment]
Np @MrUltimate!

I'm not sure I fully understand, would it be possible to provide a basic example (either a repo or a codesandbox/stackblitz style environment)?

If your animations that depend on scroller-motion are because they use the scroll position (e.g. taken from `useScrollerMotion`), you could probably fallback to the position from `useScroll` when disabling scroller-motion - but I might be misunderstanding the question.
