### ISSUE TITLE
Position: Sticky not working with scroller-motion

### ISSUE THREAD

**Issue by farhadham** [breadadams/scroller-motion#36]
Hey Everyone, I just tried the position sticky and it seems that scroller-motion somehow prevents it.
Removing <ScrollerMotion></ScrollerMotion> works normal

**Comment by breadadams** [comment]
@farhadham if I'm not mistaken this is due to a CSS spec. `position: fixed` has no effect inside an element with CSS `transform` styles (which is present on the scroller-motion wrapper).

You can try one of the following workarounds:

1. Move the fixed elements outside of the `<ScrollerMotion>` component: https://github.com/breadadams/scroller-motion/issues/4#issuecomment-663782324
2. Render the fixed element outside of the `<ScrollerMotion>` with the React Portals API: https://github.com/breadadams/scroller-motion/issues/4#issuecomment-674048873
